name: Unit Test
on:
  workflow_call:

jobs:
  unit-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      REPO_HOST: http-basic.${{ secrets.REPO_HOST }}
      REPO_USER: http-basic.${{ secrets.REPO_USER }}
      REPO_PASS: http-basic.${{ secrets.REPO_PASS }}
    strategy:
      matrix:
        php-version:
          - "8.1"
          - "8.2"
        dependency-versions:
          - "highest"
          - "lowest"

    name: PHP ${{ matrix.php-version }} (${{ matrix.dependency-versions }})
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP, Composer and Phive
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: phive
          coverage: none

      - name: Setup PHPUnit
        run: |
          phive install --trust-gpg-keys 4AA394086372C20A phpunit
          mv tools/phpunit tools/phpunit.phar

      - name: Authenticate Private Packages
        run: composer config --global $REPO_HOST $REPO_USER $REPO_PASS

      - name: Install Dependencies
        uses: ramsey/composer-install@v2
        with:
          dependency-versions: ${{ matrix.dependency-versions }}

      - name: Run PHPUnit Tests
        run: composer run-script test
